version: "3.9"

services:
  db:
    image: postgres:17
    container_name: inventario_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: inventario
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tablas.sql:/docker-entrypoint-initdb.d/tablas.sql:ro
    ports:
      - "5433:5432"

  auth-service:
    build: ./auth-service
    container_name: auth_service
    environment:
      DATABASE_URL: postgresql://postgres:12345678@db:5432/inventario
      JWT_SECRET_KEY: clave_super_secreta_cambiala_luego
    depends_on:
      - db
    ports:
      - "5001:5001"

  product-service:
    build: ./product-service
    container_name: product_service
    environment:
      DATABASE_URL: postgresql://postgres:12345678@db:5432/inventario
      JWT_SECRET_KEY: clave_super_secreta_cambiala_luego
      AUTH_SERVICE_URL: http://auth-service:5001
    depends_on:
      - db
    ports:
      - "5002:5002"

  

  gateway:
    image: nginx:alpine
    container_name: api_gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - product-service
    ports:
      - "8080:80"
      - "80:80"


volumes:
  postgres_data:
