apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: inventario
spec:
  type: NodePort
  selector:
    app: product
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 30002
